//
// Generated file, do not edit! Created by nedtool 5.6 from Packets/ExtFlowCtrl.msg.
//

#ifndef __EXTFLOWCTRL_M_H
#define __EXTFLOWCTRL_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>Packets/ExtFlowCtrl.msg:16</tt> by nedtool.
 * <pre>
 * enum XonXoff_t
 * {
 *     XON = 0;
 *     XOFF = 1;
 * }
 * </pre>
 */
enum XonXoff_t {
    XON = 0,
    XOFF = 1
};

/**
 * Class generated from <tt>Packets/ExtFlowCtrl.msg:21</tt> by nedtool.
 * <pre>
 * packet ExtFlowCtrl
 * {
 *     int action \@enum(XonXoff_t);
 * }
 * </pre>
 */
class ExtFlowCtrl : public ::omnetpp::cPacket
{
  protected:
    int action;

  private:
    void copy(const ExtFlowCtrl& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ExtFlowCtrl&);

  public:
    ExtFlowCtrl(const char *name=nullptr, short kind=0);
    ExtFlowCtrl(const ExtFlowCtrl& other);
    virtual ~ExtFlowCtrl();
    ExtFlowCtrl& operator=(const ExtFlowCtrl& other);
    virtual ExtFlowCtrl *dup() const override {return new ExtFlowCtrl(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getAction() const;
    virtual void setAction(int action);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ExtFlowCtrl& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ExtFlowCtrl& obj) {obj.parsimUnpack(b);}


#endif // ifndef __EXTFLOWCTRL_M_H

