//
// Generated file, do not edit! Created by nedtool 5.6 from Packets/IntFlowCtrl.msg.
//

#ifndef __INTFLOWCTRL_M_H
#define __INTFLOWCTRL_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>Packets/IntFlowCtrl.msg:16</tt> by nedtool.
 * <pre>
 * enum IntFlowCtrl_e
 * {
 *     INT_NEXT_FLIT = 0;
 *     INT_ROUTE_REQUEST = 1;
 *     INT_TX_REQUEST = 2;
 *     INT_RELEASE = 3;
 * }
 * </pre>
 */
enum IntFlowCtrl_e {
    INT_NEXT_FLIT = 0,
    INT_ROUTE_REQUEST = 1,
    INT_TX_REQUEST = 2,
    INT_RELEASE = 3
};

/**
 * Class generated from <tt>Packets/IntFlowCtrl.msg:23</tt> by nedtool.
 * <pre>
 * packet IntFlowCtrl
 * {
 *     int action \@enum(IntFlowCtrl_e);
 * }
 * </pre>
 */
class IntFlowCtrl : public ::omnetpp::cPacket
{
  protected:
    int action;

  private:
    void copy(const IntFlowCtrl& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IntFlowCtrl&);

  public:
    IntFlowCtrl(const char *name=nullptr, short kind=0);
    IntFlowCtrl(const IntFlowCtrl& other);
    virtual ~IntFlowCtrl();
    IntFlowCtrl& operator=(const IntFlowCtrl& other);
    virtual IntFlowCtrl *dup() const override {return new IntFlowCtrl(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getAction() const;
    virtual void setAction(int action);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IntFlowCtrl& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IntFlowCtrl& obj) {obj.parsimUnpack(b);}


#endif // ifndef __INTFLOWCTRL_M_H

