//
// Generated file, do not edit! Created by nedtool 5.6 from Packets/VirtualChannelFrame.msg.
//

#ifndef __VIRTUALCHANNELFRAME_M_H
#define __VIRTUALCHANNELFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Packets/VirtualChannelFrame.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet VirtualChannelFrame
 * {
 *     int virtualChannel;
 * }
 * </pre>
 */
class VirtualChannelFrame : public ::omnetpp::cPacket
{
  protected:
    int virtualChannel;

  private:
    void copy(const VirtualChannelFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const VirtualChannelFrame&);

  public:
    VirtualChannelFrame(const char *name=nullptr, short kind=0);
    VirtualChannelFrame(const VirtualChannelFrame& other);
    virtual ~VirtualChannelFrame();
    VirtualChannelFrame& operator=(const VirtualChannelFrame& other);
    virtual VirtualChannelFrame *dup() const override {return new VirtualChannelFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getVirtualChannel() const;
    virtual void setVirtualChannel(int virtualChannel);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const VirtualChannelFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, VirtualChannelFrame& obj) {obj.parsimUnpack(b);}


#endif // ifndef __VIRTUALCHANNELFRAME_M_H

